### ISSUE TITLE
 Installation Error (RuntimeError: Cannot find required HDF4 DLLs -- check LIBRARY_DIRS)

### ISSUE THREAD

**Issue by rmclaw88** [fhs/pyhdf#39]
### What version of pyhdf, HDF4, and Python are you using?

pyhdf version: 
HDF4 C library version:
Python version: 3.8

### What did you see instead?
RuntimeError: Cannot find required HDF4 DLLs -- check LIBRARY_DIRS

**Comment by espg** [comment]
@sabl-bot @rmclaw88  I think I fixed this issue with #40 ; it's an embarrassingly small fix (add one character to setup.py), but it hopefully will get merged so that you don't have to manually edit the setup.py file...

**Comment by swarnava-sr** [comment]
It is still showing the same error:

**RuntimeError: Cannot find required HDF4 DLLs -- check LIBRARY_DIRS**

**Comment by Conotor** [comment]
Is it just not possible to install pyhdf on some systems now?
